name: Build Release

on: 
  workflow_dispatch:

env:
  package0name: "upm-test-required-only"
  package0dir: "upm-test-required-only"
  package1name: "upm-test-all-optional-properties"
  package1dir: "upm-test-all-optional-properties"
  package2name: "upm-test-partial-objects"
  package2dir: "upm-test-partial-objects"
  package3name: "upm-test-complex-semver"
  package3dir: "upm-test-complex-semver-1"
  package4name: "upm-test-complex-semver"
  package4dir: "upm-test-complex-semver-2"
  package5name: "upm-test-complex-semver"
  package5dir: "upm-test-complex-semver-3"
  package6name: "upm-test-offspec-alcom"
  package6dir: "upm-test-offspec-alcom"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Get package0 version
        id: package0version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with: 
            path: "${{env.package0dir}}/package.json"
            prop_path: "version"
    
      - name: Get package1 version
        id: package1version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with: 
            path: "${{env.package1dir}}/package.json"
            prop_path: "version"
    
      - name: Get package2 version
        id: package2version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with: 
            path: "${{env.package2dir}}/package.json"
            prop_path: "version"
    
      - name: Get package3 version
        id: package3version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with: 
            path: "${{env.package3dir}}/package.json"
            prop_path: "version"
    
      - name: Get package4 version
        id: package4version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with: 
            path: "${{env.package4dir}}/package.json"
            prop_path: "version"
    
      - name: Get package5 version
        id: package5version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with: 
            path: "${{env.package5dir}}/package.json"
            prop_path: "version"
    
      - name: Get package6 version
        id: package6version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with: 
            path: "${{env.package6dir}}/package.json"
            prop_path: "version"
    
      - name: Set Environment Variables
        run: |
          echo "package0zip=${{ env.package0name }}-${{ steps.package0version.outputs.prop }}".zip >> $GITHUB_ENV
          echo "package1zip=${{ env.package1name }}-${{ steps.package1version.outputs.prop }}".zip >> $GITHUB_ENV
          echo "package2zip=${{ env.package2name }}-${{ steps.package2version.outputs.prop }}".zip >> $GITHUB_ENV
          echo "package3zip=${{ env.package3name }}-${{ steps.package3version.outputs.prop }}".zip >> $GITHUB_ENV
          echo "package4zip=${{ env.package4name }}-${{ steps.package4version.outputs.prop }}".zip >> $GITHUB_ENV
          echo "package5zip=${{ env.package5name }}-${{ steps.package5version.outputs.prop }}".zip >> $GITHUB_ENV
          echo "package6zip=${{ env.package6name }}-${{ steps.package6version.outputs.prop }}".zip >> $GITHUB_ENV
        
      - name: Create Zip
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "${{env.package0dir}}/"
          filename: "../${{env.package0zip}}" # make the zip file one directory up, since we start one directory in above
        
      - name: Create Zip
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "${{env.package1dir}}/"
          filename: "../${{env.package1zip}}"
        
      - name: Create Zip
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "${{env.package2dir}}/"
          filename: "../${{env.package2zip}}"
        
      - name: Create Zip
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "${{env.package3dir}}/"
          filename: "../${{env.package3zip}}"
        
      - name: Create Zip
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "${{env.package4dir}}/"
          filename: "../${{env.package4zip}}"
        
      - name: Create Zip
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "${{env.package5dir}}/"
          filename: "../${{env.package5zip}}"
        
      - name: Create Zip
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "${{env.package6dir}}/"
          filename: "../${{env.package6zip}}"
          
      - name: Make Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        with:
          tag_name: ${{ steps.package0version.outputs.prop }}
          files: |
            ${{ env.package0zip }}
            ${{ env.package1zip }}
            ${{ env.package2zip }}
            ${{ env.package3zip }}
            ${{ env.package4zip }}
            ${{ env.package5zip }}
            ${{ env.package6zip }}
