name: Build Release

on: 
  workflow_dispatch:

env:
  package0name: "upm-test-required-only"
  package1name: "upm-test-all-optional-properties"
  package2name: "upm-test-partial-objects"
  package3name: "upm-test-complex-semver"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Get package0 version
        id: package0version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with: 
            path: "${{env.package0name}}/package.json"
            prop_path: "version"
    
      - name: Get package1 version
        id: package1version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with: 
            path: "${{env.package1name}}/package.json"
            prop_path: "version"
    
      - name: Get package2 version
        id: package2version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with: 
            path: "${{env.package2name}}/package.json"
            prop_path: "version"
    
      - name: Get package3 version
        id: package3version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with: 
            path: "${{env.package3name}}/package.json"
            prop_path: "version"
    
      - name: Set Environment Variables
        run: |
          echo "package0zip=${{ env.package0name }}-${{ steps.package0version.outputs.prop }}".zip >> $GITHUB_ENV
          echo "package1zip=${{ env.package1name }}-${{ steps.package1version.outputs.prop }}".zip >> $GITHUB_ENV
          echo "package2zip=${{ env.package2name }}-${{ steps.package2version.outputs.prop }}".zip >> $GITHUB_ENV
          echo "package3zip=${{ env.package3name }}-${{ steps.package3version.outputs.prop }}".zip >> $GITHUB_ENV
        
      - name: Create Zip
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "${{env.package0name}}/"
          filename: "../${{env.package0zip}}" # make the zip file one directory up, since we start one directory in above
        
      - name: Create Zip
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "${{env.package1name}}/"
          filename: "../${{env.package1zip}}"
        
      - name: Create Zip
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "${{env.package2name}}/"
          filename: "../${{env.package2zip}}"
        
      - name: Create Zip
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "${{env.package3name}}/"
          filename: "../${{env.package3zip}}"
          
      - name: Make Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        with:
          tag_name: ${{ steps.package0version.outputs.prop }}
          files: |
            ${{ env.package0zip }}
            ${{ env.package1zip }}
            ${{ env.package2zip }}
            ${{ env.package3zip }}
